### ISSUE TITLE
'Range Slider is not a known element'

### ISSUE THREAD

**Issue by emiliogambone** [Fl0r14n/ngx-range-slider#1]
Hello,

Is this repository still active?
I've imported RangeSliderModule to my app module, and in the component i'm using like the tutorial, so ' <range-slider min="10" max="90" minValue="20" maxValue="60" step="10"></range-slider>  '.
But the console is showing me:
'ERROR Error: Uncaught (in promise): Error: Template parse errors:
'range-slider' is not a known element:
1. If 'range-slider' is an Angular component, then verify that it is part of this module.
2. If 'range-slider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'

Do I miss something?

**Comment by Fl0r14n** [comment]
The component which uses range-slider does not know who rage-slider is, cuz the module where your custom component is declared (which has range-slider declared) does not include RangeSliderModule. So if you have another angular module declared besides the AppModule, move it there in the imports
